// generated by https://github.com/Birkbjo/dhis2-open-api-ts
/* eslint-disable import/export */
export type * from './generated'
export * from './systemSettings'
// Resolve ambiguity: the app's hand-written SystemSettings takes precedence over the generated one
export type { SystemSettings } from './systemSettings'
/* eslint-enable import/export */

export type DisplayableModel = {
    id: string
    displayName: string
    disabled?: boolean
}

export type PartialLoadedDisplayableModel = {
    id: string
    displayName?: string
    disabled?: boolean
}
