// generated by https://github.com/Birkbjo/dhis2-open-api-ts
// eslint-disable-next-line import/export
export * from './generated'
// Explicit named exports (not wildcard) so they shadow the generated SystemSettings
// eslint-disable-next-line import/export
export type { SystemSettings, SystemSettingsKey } from './systemSettings'

export type DisplayableModel = {
    id: string
    displayName: string
    disabled?: boolean
}

export type PartialLoadedDisplayableModel = {
    id: string
    displayName?: string
    disabled?: boolean
}
